version: "3.9"

services: 
  user-app:
    build: ./
    command: ./wait-for-postgres.sh db ./user-app
    environment: 
      - DB_PASSWORD=test
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test
    ports:
      - 5436:5432

volumes:
  postgres_data: